global:
  resolve_timeout: 3m

route:
  group_by: ['alertname']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 24h
  receiver: 'email'
receivers:
- name: 'email'
  email_configs:
  - to: 'aldav@gkb4.ru'
    from: 'aldav99@gmail.com'
    smarthost: smtp.gmail.com:587
    auth_username: 'aldav99@gmail.com'
    auth_identity: 'aldav99@gmail.com'
    auth_password: 'password'